### ISSUE TITLE
Plugin Test

### ISSUE THREAD

**Issue by taqyon** [George-debug/obsidian-timeline#1]
Hi! 

I tested the plugin and ran into two small problems. I will describe them below and also attach technical information. If you want, you can put each problem in a separate issue for convenience.

## Some tech info
- **OS:** Mac OS Big Sur 11.4
- **Obsidian version:** v0.12.10
- **Obsidian theme:** [Discordian 0.8.6](https://github.com/radekkozak/discordian/releases)

## Issue 1
I tried using headers and it didn't work. I get the text generated instead. 

<details>
<summary>Some Pics</summary>

![Снимок экрана 2021-07-12 в 14 07 28](https://user-images.githubusercontent.com/14002721/125277882-ae6d8500-e31a-11eb-96f7-fc20bd0c4b30.png)
![Снимок экрана 2021-07-12 в 14 07 34](https://user-images.githubusercontent.com/14002721/125277887-b0374880-e31a-11eb-9c6e-2f61287dd10c.png)

</details>

## Issue 2
It seemed to me that the distance between the header (e.g. H1) and the timeline is not enough. This makes the text formatting look bad. 

I think it would be nice to add some _«air»_ between the timeline and the headings. If it's possible of course. 

<details>
<summary>Some Pics</summary>

![Снимок экрана 2021-07-12 в 14 09 09](https://user-images.githubusercontent.com/14002721/125278160-0b693b00-e31b-11eb-9848-22fe7e883ada.png)

</details>

**Comment by George-debug** [comment]
Thanks for testing ^^
I solved the issues and will appear on the next version

![image](https://user-images.githubusercontent.com/57345333/125324530-adebe300-e348-11eb-998c-e565bace9292.png)

**Comment by taqyon** [comment]
>I solved the issues and will appear on the next version

It will appear in repository right?

**Comment by taqyon** [comment]
Everything works great! 

While testing and using it, I had some thoughts. I will describe them in a separate issue and we can discuss them there. Maybe some of them will be helpful :)
