### ISSUE TITLE
Problematic interaction with Tasks plugin

### ISSUE THREAD

**Issue by Zebrazilla** [George-debug/obsidian-timeline#10]
After updating a bunch of plugins I noted a strange behavior with nodes populating in the graph that shouldn't be there. I eventually traced back this to Timeline interacting with the [Tasks](https://github.com/schemar/obsidian-tasks) plugins query results.

I use the Tasks plugin to query tasks in my daily notes, ranging all from no due dates, due within 7 days and all sorts of things. These are located on the bottom of my daily notes. These results from Tasks plugin queries do not create nodes in the graph as is the expected behavior.

With Timeline activated since the latest update, as soon as a task is toggled within a note the graph is populated with nodes from these Tasks query results, suddenly filling up the local graph with a lot of nodes. If Obsidian is restarted the graph is no longer populated, but as soon as another task is toggled it will populate with these again.

Looking in the latest changelog I see _"The plugin creates nodes between files"_, could this be the cause for this behavior? Would it be possible to detect if Tasks is used with Timeline, or even a setting that can be toggled, to prevent this from happening?

Thank you for a great plugin.

**Comment by George-debug** [comment]
Hello! I tried to recreate it and I couldn't! Everything works as intended.
Would you please give me a test vault or something where I can see it?

I'll continue to test it and if I find it I'll post another comment here.

**Comment by George-debug** [comment]
Well, I deactivated that feature until I find another solution.
