### ISSUE TITLE
Plugin does not activate on iOS

### ISSUE THREAD

**Issue by melbv** [George-debug/obsidian-timeline#11]
Hi @George-debug 
I just realised that the plugin would not load after its last update on iOS. I mostly use Obsidian for mobile and cannot use it anymore. It works fine on my Mac though.
Would you know why and/or require more info on my Obsidian setup?
Thanks in advance

---

iOS: 14.8
Obsidian for iOS: 1.0.4

**Comment by George-debug** [comment]
HI @melbv
I can't test it on iOS. I deactivated that feature until I find another solution.
Now I hope it works for others too, not just for me.

**Comment by melbv** [comment]
Hi @George-debug 
Thanks for deactivate - i have updated the plugin and have the same issue not being able to load it on iOS...
Not sure whether it can be the plugin's fault or a problem of interactions with other plugins. Do you happen to know of conflicts with other plugins?

**Comment by George-debug** [comment]
I had 1 conflict with the "tasks" plugin (I think it is solved) and with the "Timelines" plugin (both plugins use the same tag).

**Comment by George-debug** [comment]
I'm soo sorry I can't test in on iOS!
In half an hour I release a CSS file that doesn't need any plugin to work. I don't know if mobile versions are allowed to add snippets :(

**Comment by melbv** [comment]
no worries at all - at least you know that there is an issue with it. I'll be patient on my end and hopefully you can resolve this quickly.
Good luck for the dev!

**Comment by George-debug** [comment]
HI @melbv 
Can you list all your plugins, please? In case it has nothing to do with iOS.

**Comment by melbv** [comment]
HI George
see below

- admonition
- advanced tables
- buttons
- citations
- dataview
- dice roller
- dynamic table of contents
- emoji shortcodes
- find unlinked files and unresolved links
- ledger
- map view
- markdown formatting assistant
- metaedit
- metatable
- paste url into selection
- pocket integration
- quickadd
- tasks
- templater

Hope this helps
M 


2 Oct 2021, 20:29 by ***@***.***:

**Comment by George-debug** [comment]
@melbv, thank you soo much! :)

**Comment by melbv** [comment]
No problems - let me know if you find anything

2 Oct 2021, 21:02 by ***@***.***:

**Comment by Signynt** [comment]
Also looking forward to it, it's a great plugin and I would really love to be able to use it on my iPad as well!

**Comment by Peingxious** [comment]
I hope it can support IOS, which is a good process recording software, so I don't need to do process recording with title inside title. Thank you ~

**Comment by George-debug** [comment]
For those with IOS or MAC, [this](https://github.com/George-debug/obsidian-timeline/tree/master/src/style/snippet) is the only solution for now.

**Comment by Signynt** [comment]
[My fork](https://github.com/Signynt/obsidian-timeline) using an older plugin and some minor changes works fine for me across platforms (including iOS and Mac, but also Android and Windows)
