### ISSUE TITLE
similar plugin for flow chart possible

### ISSUE THREAD

**Issue by ananthuthilakan** [George-debug/obsidian-timeline#16]
hi developer,
the timeline plugin is super great , because its super simple and doesnt interrupt workflow.

is it possible to make a similar plugin for simple flow chart  (if possible with one or 2 branches)

thank you

**Comment by George-debug** [comment]
hi kind stranger,
I made this plugin because I need it. I'm sorry, but I don't have the time necessary to write another plugin.

thank you for your issue
