### ISSUE TITLE
have a display BUG in the read mode

### ISSUE THREAD

**Issue by MugenLee** [George-debug/obsidian-timeline#17]
when display the list , the symbol can not display

as the pic

![image](https://user-images.githubusercontent.com/91043731/155260917-f3828501-aa6f-42f3-9bcd-42a5e08f72a0.png)

**Comment by George-debug** [comment]
I've tested it, and for me, it works perfectly.

~~~markdown
![[test2]]


```timeline
+ </br>
+ title
+ hey
![[test2]]

+ </br>
+ 
+ 

+ </br>
+ 
+ 
```
~~~

<img width="1033" alt="image" src="https://user-images.githubusercontent.com/57345333/181367579-06207843-c6e4-445c-9fd6-e292b3943596.png">

**Comment by MugenLee** [comment]
> I've tested it, and for me, it works perfectly.
> 
> ```gfm
> ![[test2]]
> 
> 
> ```timeline
> + </br>
> + title
> + hey
> ![[test2]]
> 
> + </br>
> + 
> + 
> 
> + </br>
> + 
> + 
> ```
> ```
> 
> <img alt="image" width="1033" src="https://user-images.githubusercontent.com/57345333/181367579-06207843-c6e4-445c-9fd6-e292b3943596.png">

good, thanks 
best job!
