### ISSUE TITLE
[request] Any chance to have footnote supported in header and body?

### ISSUE THREAD

**Issue by zfei** [George-debug/obsidian-timeline#18]

**Comment by George-debug** [comment]
Well, as far as I understand, I can't render that block to work with footnotes, not even to create links.

I recommend you use [this snipped](https://github.com/George-debug/obsidian-timeline/tree/master/src/style/snippet) instead.

**Comment by zfei** [comment]
Wow, great to know about it, not bad at all.

While you are here --

- Does that css snippet has to be applied page-wide or can we end it somewhere with a mark?
- Looks like the snippet style only shows up in read mode, could it be enabled in live view as well?

Thanks.

**Comment by zfei** [comment]
Also I'm getting this parentheses-like list style in read mode, which might come from my theme. Could you give a hint on how to override that within the timeline scope? Much appreciated.

![image](https://user-images.githubusercontent.com/1736058/181517454-a705b3d0-11c1-49e8-904c-3a795da70fc0.png)

**Comment by George-debug** [comment]
Can you write the theme's name?

**Comment by zfei** [comment]
It’s Blue Topaz with “topaz nord” color theme in Style Setting
