### ISSUE TITLE
Suggestion: Move the text to the second line in `line for time`

### ISSUE THREAD

**Issue by taqyon** [George-debug/obsidian-timeline#2]
## Hi! 
I thought it would be cool to be able to move the _line for time_ text to a new line with the command `<br>` for example. This will allow you to add long expressions to the header without affecting the reading. 

As you may have noticed, if you add too long text to the header, the whole time line starts to "plush". I recorded a short video with an example below.

## Video example

https://user-images.githubusercontent.com/14002721/125280292-89c6dc80-e31d-11eb-83ea-708b11675cbf.mov

**Comment by George-debug** [comment]
Hello!
I hope this solves the problem! This change will appear in the next version
![image](https://user-images.githubusercontent.com/57345333/125325497-ada01780-e349-11eb-8a0f-94bbe4ca1a9a.png)

**Comment by taqyon** [comment]
Everything works! Everything is cool, thank you!
