### ISSUE TITLE
Text vanishing after inserting YAML

### ISSUE THREAD

**Issue by aarontimo** [George-debug/obsidian-timeline#26]
Hi there,

Thank you for the great plugin!

I'm just having some trouble making the plugin work correctly. After adding 
`---
cssclass: timeline
---`
to the top of the note, all the remaining text in the note (that is not part of the timeline) can no longer be seen. The text is still there because the word count reflects this and it will appear in reading view but I can't edit the remaining content.

I thought it might have to do with live preview so I switched this off. I've also tried toggling between editing and reading mode and toggling between live preview and source mode.

Any help or advice is greatly appreciated.

**Comment by George-debug** [comment]
Hi there,

this is not how you use the plugin, that's how the snippet works. Someone requested a snippet for unordered lists to look like a timeline.

**Comment by aarontimo** [comment]
My apologies. I misunderstood the first line of instructions - I read it as a preferred way to create a timeline. Got it working now. Thanks again!
