### ISSUE TITLE
spaced-paragraph and white/black classes don't seem to do anything

### ISSUE THREAD

**Issue by swehba** [George-debug/obsidian-timeline#4]
This timeline text (no `spaced-paragraph` class):

~~~
```timeline
+ time1
+ header
+ description line 1

description line 2

description line 3

+ time2
+ header
+ description line 1

description line 2

description line 3
```
~~~

And this timeline text (with a `spaced-paragraph` class):

~~~
```timeline
[spaced-paragraph]
+ time1
+ header
+ description line 1

description line 2

description line 3

+ time2
+ header
+ description line 1

description line 2

description line 3
```
~~~

Appear to render exactly the same. Is the `spaced-paragraph` class supposed to change the way the text renders?

**Comment by George-debug** [comment]
`spaced-paragraph` is for multiple lines and hard to read paragraphs.

![image](https://user-images.githubusercontent.com/57345333/129947007-6c28444f-2676-420c-b8b6-5084216fba46.png)

`I'm waiting for your reply in case you still can't see the difference on your device`

**Comment by swehba** [comment]
OK, now I understand. `spaced-paragraph` give a bit more room to lines *within* a paragraph, not *between* paragraphs. Given that, I can now see a different, but it is very slight.

How about `white/black`, what is that supposed to do?

**Comment by George-debug** [comment]
Thank you for telling me this! I will change `spaced-paragraph` to `spaced-lines`.

I wanted my class system to be tested before version `1.0.0` where I'll use this system to change the timeline type of components so the change is done through CSS.

My line is nothing more than a color with opacity, so it matches the theme.
My CSS should adjust to your theme anyway, regardless of light/dark.
If you have a theme that makes the timeline vertical line to be white, even tho you want it to be black, you can use `black` class.
This situation is highly unlikely.
