### ISSUE TITLE
[Feature Request]Support formatting out of codeblock

### ISSUE THREAD

**Issue by oshino29** [George-debug/obsidian-timeline#5]
Thanks for making  this great plugin. A structured timeline view will be extremely useful for chronologically taking evergreen notes on researchers, academic debates, status of specic fields and so on.

However I was disappointed to find that **linking inside codeblocks isn't fully supported by Obsidan**. The links are clickable, but won't create a link between notes in graph and notes won't appear in the "linked mentions" panel. So it would be great for this plugin to read formatting outside codeblocks to fit the Zettelkasten-philosophy of Obsidian.

One suggestion on formatting is  nested bullet points, which has also a clear view in edit mode:
<img width="766" alt="21-07-17_K04RPq5a" src="https://user-images.githubusercontent.com/20519508/126035828-54b1ba06-1282-4953-a2ee-bb8b9396485e.png">

**Comment by dpurnomo** [comment]
I would second this. Timeline will be much more useful if we can link the dates and characters in it.

**Comment by George-debug** [comment]
Oh, I didn't know this :)
I'll learn more about the API and do this
When I'm done coding this, I'll post a screenshot here before releasing it and close this issue

**Comment by George-debug** [comment]
I did it! I read the API and some code and

![image](https://user-images.githubusercontent.com/57345333/129940348-f8da0460-5ed5-40ea-9f80-4bc06b85a899.png)

Now I want to clean this approach because the source is spaghetti code

**Comment by ryuitxi** [comment]
¿Still need to be in a codeblocks  with that solution?

**Comment by George-debug** [comment]
I can make a CSS file for it
This project started as CSS [here](https://forum.obsidian.md/t/timeline-custom-css/20406) (it's not responsive unlike the current version)

**Comment by George-debug** [comment]
I will close this issue after I post the CSS and SASS here
It's hard and counterproductive to play outside the code block

**Comment by ryuitxi** [comment]
May I ask why is it hard and counterproductive?

**Comment by George-debug** [comment]
I would like to read your reply to this:

I read that this feature was a `"popular demand"` in 2020 and Jan 2021.
They added it in v0.10.12, making it easier for people to write plugins and decrease the incompatibility between plugins.

I have 2 problems if I decide to add this to my plugin:
- Do I need a setting that allows you to do this by default (checking every DOM element until I find the timeline) or a setting that adds this to your vault?
- How can I know that this list of lists of lists is a timeline? (my solution is to add a distinctive header before).

To avoid this, I'll use [taqyon's idea](https://github.com/George-debug/obsidian-timeline/issues/3) to make everything readable and use the new code I tested for proper node linking.

`+ For me, writing a piece of code that adds a class to that list of lists of lists is the same as adding a class to a page vault and use the CSS SNIPPETS feature.`

**Comment by George-debug** [comment]
I kept this issue open for quite a while.

I made [this snippet](https://github.com/George-debug/obsidian-timeline/tree/master/src/style/snippet) and should work nicely.

**Comment by lkjanicki** [comment]
Hi, first of all, thanks for the great plugin! Secondly, after reading this conversation I am not sure if at the end the links inside the plugin should work or not? From the screenshot you posted, it seemed to me as if it should work but giving it a try I am afraid it doesn't work me:

![image](https://user-images.githubusercontent.com/54234538/212529974-d05336a4-e466-4b0d-9474-41d28f8909c6.png)

I'm using Obsidian in version: 1.1.9, and plugin in version: 1.1.0.
