### ISSUE TITLE
[feature request] Timelines spacing proportional to the dates

### ISSUE THREAD

**Issue by rui-nar** [George-debug/obsidian-timeline#7]
Hi there
Is there a way to be able to have kind of spacing between paragraphs wich is proportional to the sate spacing, ie, if I have:Jan, Feb, Dec that Jan & Feb are close to each other and Dec is further down.
Of course this should be optional and there would be the need to use date formats and a date format qualifier but just managing this via empty lines should be doable.

What do you think ??
Rui

**Comment by George-debug** [comment]
Hi there

**Comment by George-debug** [comment]
Hi there!
 
 I never thought of it. For me, your idea is great for a horizontal timeline, giving you the time perspective regarding the distance between events

**Comment by rui-nar** [comment]
Hey
For sure I would prefer to have it in a very visual horizontal line but I haven't been able to find any plugin that does it or a js library that enables it ...
Your plugin is the next best thing hence my request.

Maybe some scrolling would be require but maybe limiting the bigger gaps to: 
```

...

```
(Empty lines with "..." in between) It could maybe help reduce the scrolling.

What do you think ?

**Comment by George-debug** [comment]
I'll keep this idea in mind **after** I release this new version and post the design here :)

**Comment by blackpeasy** [comment]
+1
Proportional horizontal timeline would be killer! Not just for dates but also clock time etc.
This feature is really something that is missing in Obsidian (and the other timeline plugin is too complicated in my opinion).

**Comment by Ki-HH** [comment]
Yes, Proportional horizontal timeline would be killer!

**Comment by rui-nar** [comment]
Hey @George-debug , does this mean the feature will be available in an upcoming release ?
If so, how does one use this ?
Thanks
